### ISSUE TITLE
Epic for Draw-Website

### ISSUE THREAD

**Issue by MouhamadBilal** [MouhamadBilal/draw-website#1]
for this project I need to do those things:

- [x] Create a new repository
- [x] Create a new Symfony project
- [x] Commit the new project 
- [x] Add my manager to the project as collaborator
- [x] Create my first controller
- [x] Create a static page with a draw (focus on template) #2 
- [x] Create my Pull Request #2 
- [x] Setup Doctrine
- [x] Create the Database
- [x] Merge the pull request
- [x] Create migrations
- [x] Execute migrations
- [x] Create table draw
- [x] Create an EasyAdmin #3 
- [x] Create a form #5 
- [x] Configure admin interface
- [x] Stock Data
- [x] Create the Add file
- [x] Link my app and my DB
- [x] See if my draws can be displayed on templates
- [x] refacto le code
- [x] utiliser le chemin "/ " pour accéder aux publications 
- [x] créer des champs pour les noms, descriptions et date pour chaque publications
- [ ] Delete images from file system when it's delete by user and admin 
- [ ] La pagination
- [ ] avoir de la modération avec l'admin qui autorise la publication d'une image depuis son interface
- [ ] ajouter une colonne `state` à la table draw
- [ ] Display image before publishing and editing in admin
